language: node_js
before_install:
  - yarn
script:
  - yarn run build
after_success:
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git add README.md
  - git commit -m "Automatic update of README.md"
  - git remote add origin-readme https://$GH_TOKEN@github.com/mohebifar/made-in-iran.git > /dev/null 2>&1
  - git push --quiet --set-upstream origin-readme master
